### ISSUE TITLE
  Ipad air 3 don't flash 

### ISSUE THREAD

**Issue by Ricco59163** [palera1n/py-rewrite#3]
hi all , can install palerain on Ipad air 3 with ios 15.6rc ? don't flash for me

**Comment by plooshi** [comment]
no, that is A12 which is not checkm8. you need an A8-A11 device to use palera1n.

**Comment by Ricco59163** [comment]
> no, that is A12 which is not checkm8. you need an A8-A11 device to use palera1n.

thx Bro,

Wait and see

**Comment by BigBoiMan123** [comment]
A12 will never be supported
